import Head from 'next/head'
import { GiAbstract047 } from "react-icons/gi"


export default function Home() {
  return (
    <div>
      <Head>
        <title>Raymond Huang Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>myPortfolio</h1>
            <ul className='flex items-center'>
              <li><GiAbstract047 className='cursor-pointer text-2xl' /></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Raymond Huang</h2>
            <h3 className='text-2xl py-2'>Developer and Designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>I am currently looking for a frontend developement role. I am also looking for a designer role</p>
          </div>
        </section>
      </main>
    </div>
  )
} 
